### PR TITLE
#15 poker phaser

### PR DESCRIPTION
**Pull request by m0rio0818**

### CODE REVIEW

**Comment by largearth** [comment]
[10:27:27] src/games/common/preloadScene.ts(3,1): error TS6133: 'Table' is declared but its value is never read.
[10:27:27] src/games/pokerScene.ts(100,21): error TS2345: Argument of type 'string | number' is not assignable to parameter of type 'string | string[]'.
[10:27:27]   Type 'number' is not assignable to type 'string | string[]'.
[10:27:27] src/model/poker/pokerGameDecision.ts(1,26): error TS2307: Cannot find module '../common/GameDecision.js' or its corresponding type declarations.
[10:27:27] src/model/poker/pokerPlayer.ts(82,5): error TS2416: Property 'getHandScore' in type 'pokerPlayer' is not assignable to the same property in base type 'Player'.
[10:27:27]   Type '(dealer: pokerPlayer) => PokerHandType' is not assignable to type '(player?: pokerPlayer | undefined) => number'.
[10:27:27]     Type 'string' is not assignable to type 'number'.
[10:27:27]       Type 'string' is not assignable to type 'number'.
[10:27:27] src/model/poker/pokerTable.ts(25,5): error TS2416: Property 'players' in type 'pokerTable' is not assignable to the same property in base type 'Table'.
[10:27:27]   Type 'pokerPlayer[]' is not assignable to type 'Player[]'.
[10:27:27]     Type 'pokerPlayer' is not assignable to type 'Player'.
[10:27:27]       Types of property 'getHandScore' are incompatible.
[10:27:27]         Type '(dealer: pokerPlayer) => PokerHandType' is not assignable to type '(player?: pokerPlayer | undefined) => number'.
[10:27:27] src/model/poker/pokerTable.ts(394,5): error TS2416: Property 'evaluateMove' in type 'pokerTable' is not assignable to the same property in base type 'Table'.
[10:27:27]   Type '(player: pokerPlayer, userData?: PokerActionType | undefined) => void' is not assignable to type '(player: Player) => void'.
[10:27:27]     Types of parameters 'player' and 'player' are incompatible.
[10:27:27]       Type 'Player' is missing the following properties from type 'pokerPlayer': Cards, maxValue, playerHandStatus, pairsOfTwoList, and 14 more.
[10:27:27] Error: Command "npm run build" exited with 2
[10:27:28]

**Comment by SouthernMinami** [comment]
レビュー遅くなってすみません。
Poker一通りプレイすることができました。最終結果が表形式になってるのすごく見やすいです！
あと未使用変数などのエラー潰すのと、できれば最終結果画面にボタン追加するだけだと思います。エラー治し切るのしんどそうだったらお力添えします！

**Comment by largearth** [comment]
src/games/blackjackScene.ts(627,7): error TS2365: Operator '>' cannot be applied to types 'string \| number' and 'number'.
src/model/poker/pokerGameDecision.ts(1,26): error TS2307: Cannot find module '../common/GameDecision.js' or its corresponding type declarations.

**Review by largearth — APPROVED** [review]
確認しました。

**Pull request merged**
