### PR TITLE
#15 poker proto

### LINKED ISSUE #15: Porkerの実装
## 概要
ポーカーのゲームの実装

## タスク
- [x] Modelの実装
    - [x] 手札の役判定ロジック
         - [x] 多数が、no pair, two pair だった時の勝利プレイヤー判定
    - [x] foldした際にターン中スキップされるロジック
    - [x] 最小ベット額より所持金が小さかったらallin => fold状態にする。
    - [ ] 所持金 -にならないように設計する。
    - [x] aiの実装 
         - [x] ワンペア、ツーペアの場合は、hit, raise
         - [x] それ以外、基本passできたらする。無理ならhit
         - [x] 手札が弱い => dropさせたい。
- [x] Viewの実装
- [x] Contlloerの実装

### PR DESCRIPTION
**Pull request by m0rio0818**
ポーカーのプロトを作成しました。ゲーム内バグはまだあるので、この後issueに書いて修正していきます。

### CODE REVIEW

**Review by SouthernMinami — COMMENTED** [review]
ラウンド制や小さいバグを除けば、問題なくPokerプレイできることが確認できました！
他のゲームも問題なく起動できるので、コンフリクト解消したら一旦マージで大丈夫だと思います。

**Review by SouthernMinami — COMMENTED** [review]
↑あとデプロイを妨げてるエラーが消えれば

**Review by largearth — DISMISSED** [review]

**Comment by daxchx** [comment]
確認しました。
↓Deploymentエラーを解消する必要がありそうです。
https://vercel.com/daxchxs-projects-8ee03b67/playing-card/28ZSU2GXVZXHxi5RyXsxFeHuCJ6x

**Review by largearth — COMMENTED** [review]
確認しました。
↓Deploymentエラーを解消する必要がありそうです。
https://vercel.com/daxchxs-projects-8ee03b67/playing-card/28ZSU2GXVZXHxi5RyXsxFeHuCJ6x

**Comment by largearth** [comment]
[22:58:09] Running build in Washington, D.C., USA (East) – iad1
[22:58:11] Cloning github.com/Frontend-teamDevC/playing-card (Branch: #15_poker_proto, Commit: c87c7da)
[22:58:12] Cloning completed: 687.686ms
[22:58:14] Restored build cache
[22:58:14] Running "vercel build"
[22:58:14] Vercel CLI 33.0.1
[22:58:16] Installing dependencies...
[22:58:17] 
[22:58:17] up to date in 1s
[22:58:17] 
[22:58:17] 111 packages are looking for funding
[22:58:17]   run `npm fund` for details
[22:58:17] Detected `package-lock.json` generated by npm 7+
[22:58:17] Running "npm run build"
[22:58:18] 
[22:58:18] > app@0.0.0 build
[22:58:18] > tsc && vite build
[22:58:18] 
[22:58:21] src/controller/PokerController.ts(17,18): error TS2339: Property 'renderFinalResultsModal' does not exist on type 'typeof PokerController'.
[22:58:21] src/controller/controller.ts(9,33): error TS1261: Already included file name '/vercel/path0/src/controller/pokerController.ts' differs from file name '/vercel/path0/src/controller/PokerController.ts' only in casing.
[22:58:21]   The file is in the program because:
[22:58:21]     Imported via './pokerController' from file '/vercel/path0/src/controller/controller.ts'
[22:58:21]     Matched by include pattern 'src' in '/vercel/path0/tsconfig.json'
[22:58:21]     Matched by include pattern 'src' in '/vercel/path0/tsconfig.json'
[22:58:21] src/games/common/pokerButton.ts(18,13): error TS2345: Argument of type '{ style: { color: string; fontSize: string; fontFamily: string; }; }' is not assignable to parameter of type 'TextStyle'.
[22:58:21]   Object literal may only specify known properties, and 'style' does not exist in type 'TextStyle'.
[22:58:21] src/games/pokerScene.ts(318,17): error TS2345: Argument of type '{ style: { fontSize: string; color: string; fontFamily: string; }; }' is not assignable to parameter of type 'TextStyle'.
[22:58:21]   Object literal may only specify known properties, and 'style' does not exist in type 'TextStyle'.
[22:58:21] src/games/pokerScene.ts(335,17): error TS2345: Argument of type '{ style: { fontSize: string; color: string; fontFamily: string; }; }' is not assignable to parameter of type 'TextStyle'.
[22:58:21]   Object literal may only specify known properties, and 'style' does not exist in type 'TextStyle'.
[22:58:21] src/games/pokerScene.ts(368,21): error TS2345: Argument of type '{ style: { fontSize: string; color: string; fontFamily: string; }; }' is not assignable to parameter of type 'TextStyle'.
[22:58:21]   Object literal may only specify known properties, and 'style' does not exist in type 'TextStyle'.
[22:58:21] src/games/pokerScene.ts(434,21): error TS2345: Argument of type '{ style: { fontSize: string; color: string; fontFamily: string; }; }' is not assignable to parameter of type 'TextStyle'.
[22:58:21]   Object literal may only specify known properties, and 'style' does not exist in type 'TextStyle'.
[22:58:21] src/model/poker/pokerPlayer.ts(82,5): error TS2416: Property 'getHandScore' in type 'pokerPlayer' is not assignable to the same property in base type 'Player'.
[22:58:21]   Type '(dealer: pokerPlayer) => PokerHandType' is not assignable to type '() => number'.
[22:58:21]     Target signature provides too few arguments. Expected 1 or more, but got 0.
[22:58:21] src/model/poker/pokerPlayer.ts(219,16): error TS6133: 'pairsOfFour' is declared but its value is never read.
[22:58:21] src/model/poker/pokerTable.ts(23,5): error TS2416: Property 'players' in type 'pokerTable' is not assignable to the same property in base type 'Table'.
[22:58:21]   Type 'pokerPlayer[]' is not assignable to type 'Player[]'.
[22:58:21]     Type 'pokerPlayer' is not assignable to type 'Player'.
[22:58:21]       Types of property 'getHandScore' are incompatible.
[22:58:21]         Type '(dealer: pokerPlayer) => PokerHandType' is not assignable to type '() => number'.
[22:58:21] src/model/poker/pokerTable.ts(152,21): error TS6133: 'maxThreeCardIndex' is declared but its value is never read.
[22:58:21] src/model/poker/pokerTable.ts(405,5): error TS2416: Property 'evaluateMove' in type 'pokerTable' is not assignable to the same property in base type 'Table'.
[22:58:21]   Type '(player: pokerPlayer, userData?: PokerActionType | undefined) => void' is not assignable to type '(player: Player) => void'.
[22:58:21]     Types of parameters 'player' and 'player' are incompatible.
[22:58:21]       Type 'Player' is missing the following properties from type 'pokerPlayer': Cards, maxValue, playerHandStatus, pairsOfTwoList, and 14 more.
[22:58:21] src/model/poker/pokerTable.ts(673,5): error TS2416: Property 'getTurnPlayer' in type 'pokerTable' is not assignable to the same property in base type 'Table'.
[22:58:21]   Type '() => pokerPlayer' is not assignable to type '() => Player'.
[22:58:21]     Type 'pokerPlayer' is not assignable to type 'Player'.
[22:58:21] src/view/PokerView.ts(3,1): error TS6133: 'Phaser' is declared but its value is never read.
[22:58:21] src/view/PokerView.ts(12,15): error TS6133: 'modal' is declared but its value is never read.
[22:58:21] src/view/PokerView.ts(247,13): error TS6133: 'players' is declared but its value is never read.
[22:58:21] Error: Command "npm run build" exited with 2
[22:58:21]

**Pull request closed without merging**
